/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
calc_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	char* q;
	if(argp->c == 1){
		q = "+";
	}else if(argp->c == 2){
		q = "-";
	}else if(argp->c == 3){
		q = "*";
	}else if(argp->c == 4){
		q = "/";
	}else {
		printf("Wrong operand input");
	}
	
	printf("Calculate: %f %c %f \n",argp->a, *q,argp->b);
	switch(argp-> c){
		case 1:
			result = argp->a + argp->b;
		break;
		case 2:
			result = argp->a - argp->b;
		break;
		case 3:
			result = argp->a * argp->b;
		break;
		case 4:
			result = argp->a / argp->b;
		break;
	}

	return &result;
}
