/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int number_input(){
	int x;
	printf("Enter number: ");
	scanf("%d",&x);
	return x;
}

int op_input(){
	int x;
	printf("\nPick Operand to perform: ");
	printf("\n1.Add\n2.Sub\n3.Mult\n4.Division.");
	scanf("%d",&x);
	return x;
}


void
calc_prog_1(char *host,float x,float y, int z)
{
	CLIENT *clnt;
	float  *result_1;
	input  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	calc_1_arg.a = x;
	calc_1_arg.b = y;
	calc_1_arg.c = z;
	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Result: %f\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int num1 = number_input();
	int num2 = number_input();
	int pick = op_input();
	calc_prog_1 (host,num1,num2,pick);
exit (0);
}


